baseURL = 'https://webauthn.academy/'
languageCode = 'en-us'
title = 'Webauthn Academy'
theme = 'webauthn'
disableKinds = ["taxonomy", "term"]

[markup.highlight]
style = "borland"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Browser'
pageRef = '/browser-apis/'
weight = 20

[[menus.main]]
name = 'Elixir'
pageRef = '/elixir/'
weight = 30

[[menus.main]]
name = 'Golang'
pageRef = '/golang/'
weight = 40

[[menus.main]]
name = 'Contact'
pageRef = '/contact/'
weight = 50

[[menus.footer]]
name = 'Changelog'
pageRef = '/changelog/'
weight = 50

[[menus.footer]]
name = 'Webauthn Browser APIs'
pageRef = '/browser-apis/'
weight = 10

[[menus.footer]]
name = 'Implementing Webauthn in Elixir'
pageRef = '/elixir/'
weight = 20

[[menus.footer]]
name = 'Implementing Webauthn in Golang'
pageRef = '/golang/'
weight = 30

[[menus.footer]]
name = 'Contact and licensing'
pageRef = '/contact/'
weight = 40

[markup.goldmark.renderer]
unsafe= true
