baseURL = 'https://webauthn.academy/'
languageCode = 'en-us'
title = 'Webauthn Academy'
theme = 'webauthn'
disableKinds = ["taxonomy", "term"]

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Changelog'
pageRef = '/changelog/'
weight = 20

[markup.goldmark.renderer]
unsafe= true
